use serde::{Deserialize, Serialize};

/// Role carried by a transcript message.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[serde(rename_all = "snake_case")]
pub enum MessageRole {
    /// System messages are instructions or context provided by the system, often can be influenced by the user
    System,

    /// Developer messages are instructions or context provided by developers, never directly influenced by the user
    ///
    /// This is a more recent addition to allow better protections against prompt injection attacks by
    /// distinguishing user-provided instructions (system) from developer-provided instructions (developer).
    Developer,

    /// User messages are inputs provided by the user
    User,

    /// Assistant messages are outputs generated by the model in response to user input or instructions.
    Assistant,

    /// Tool messages are generated by the model to indicate an intended tool call, and include tool call metadata.
    Tool,
}

/// A single message in a transcript.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[cfg_attr(feature = "schema", derive(schemars::JsonSchema))]
#[serde(rename_all = "lowercase")]
pub struct TranscriptMessage {
    pub role: MessageRole,
    pub content: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_call_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_name: Option<String>,
}

impl TranscriptMessage {
    /// Create a transcript message without tool metadata.
    pub fn new(role: MessageRole, content: impl Into<String>) -> Self {
        Self {
            role,
            content: content.into(),
            tool_call_id: None,
            tool_name: None,
        }
    }

    /// Create a transcript message with optional tool metadata.
    pub fn with_tool_metadata(
        role: MessageRole,
        content: impl Into<String>,
        tool_call_id: Option<String>,
        tool_name: Option<String>,
    ) -> Self {
        Self {
            role,
            content: content.into(),
            tool_call_id,
            tool_name,
        }
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn message_role_serde_roundtrip() {
        for role in [
            MessageRole::System,
            MessageRole::User,
            MessageRole::Assistant,
            MessageRole::Tool,
        ] {
            let json = serde_json::to_string(&role).unwrap();
            let parsed: MessageRole = serde_json::from_str(&json).unwrap();
            assert_eq!(role, parsed);
        }
    }

    #[test]
    fn transcript_message_serde_roundtrip() {
        let message = TranscriptMessage::with_tool_metadata(
            MessageRole::Tool,
            "hello",
            Some("call-1".into()),
            Some("io.bash".into()),
        );

        let json = serde_json::to_string(&message).unwrap();
        let parsed: TranscriptMessage = serde_json::from_str(&json).unwrap();

        assert_eq!(parsed.role, MessageRole::Tool);
        assert_eq!(parsed.content, "hello");
        assert_eq!(parsed.tool_call_id.as_deref(), Some("call-1"));
        assert_eq!(parsed.tool_name.as_deref(), Some("io.bash"));
    }
}
