use crate::{InferenceMeta, InferenceOutputDelta, InferenceUpdate, ModelId, StreamSeq};
use serde::{Deserialize, Serialize};

/// An event emitted while a node executes an inference operation.
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub enum InferenceRunEvent {
    /// The node started executing the inference request.
    RunStarted {
        /// Resolved execution identity.
        meta: InferenceMeta,
    },
    /// The node completed one inference round.
    RoundCompleted {
        /// Resolved execution identity.
        meta: InferenceMeta,
    },
    /// The node emitted one progressive output delta.
    Output {
        /// Resolved execution identity.
        meta: InferenceMeta,
        /// Monotonic output sequence number.
        seq: StreamSeq,
        /// Typed output generated by the node.
        output: InferenceOutputDelta,
    },
    /// The node completed the inference operation successfully.
    RunCompleted {
        /// Resolved execution identity.
        meta: InferenceMeta,
        /// Total number of output events generated by the node.
        total_outputs: StreamSeq,
    },
    /// The node cancelled the inference operation.
    Cancelled {
        /// Resolved execution identity.
        meta: InferenceMeta,
        /// Optional cancellation reason.
        reason: Option<String>,
    },
    /// The node failed the inference operation.
    Failed {
        /// Resolved execution identity.
        meta: InferenceMeta,
        /// Human-readable failure detail.
        error: String,
    },
}

impl From<InferenceUpdate> for InferenceRunEvent {
    fn from(update: InferenceUpdate) -> Self {
        match update {
            InferenceUpdate::Started(update) => Self::RunStarted { meta: update.meta },
            InferenceUpdate::Progress(update) => Self::Output {
                meta: update.meta,
                seq: update.seq,
                output: update.output,
            },
            InferenceUpdate::Completed(update) => Self::RunCompleted {
                meta: update.meta,
                total_outputs: StreamSeq::first(),
            },
            InferenceUpdate::Cancelled(update) => Self::Cancelled {
                meta: update.meta,
                reason: update.reason,
            },
            InferenceUpdate::Failed(update) => Self::Failed {
                meta: update.meta,
                error: update.error,
            },
        }
    }
}

/// An event emitted while a node loads a model.
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum LoadModelEvent {
    /// The node started loading the model.
    Started {
        /// Model being loaded.
        model_id: ModelId,
    },
    /// The node loaded the model successfully.
    Completed {
        /// Model now available for inference.
        model_id: ModelId,
    },
    /// The node failed to load the model.
    Failed {
        /// Model the node attempted to load.
        model_id: ModelId,
        /// Human-readable failure detail.
        error: String,
    },
}

/// An event emitted while a node unloads a model.
#[derive(Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum UnloadModelEvent {
    /// The node started unloading the model.
    Started {
        /// Model being unloaded.
        model_id: ModelId,
    },
    /// The node unloaded the model successfully.
    Completed {
        /// Model removed from memory.
        model_id: ModelId,
    },
    /// The node failed to unload the model.
    Failed {
        /// Model the node attempted to unload.
        model_id: ModelId,
        /// Human-readable failure detail.
        error: String,
    },
}
