use serde::{Deserialize, Serialize};

/// Token accounting for an inference operation.
#[derive(
    Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize, schemars::JsonSchema,
)]
pub struct TokenUsage {
    /// The number of input tokens processed by the model.
    pub input_tokens: usize,

    /// The number of output tokens generated by the model.
    pub output_tokens: usize,

    /// The total token count for the request.
    pub total_tokens: usize,
}

/// Optional performance metrics recorded for a completed inference operation.
#[derive(Debug, Clone, Copy, Default, PartialEq, Serialize, Deserialize, schemars::JsonSchema)]
pub struct PerformanceMetrics {
    /// The total request duration in milliseconds.
    pub total_duration_ms: u64,

    /// The average prompt processing throughput, if known.
    pub input_tokens_per_second: Option<f32>,

    /// The average generation throughput, if known.
    pub output_tokens_per_second: Option<f32>,
}
